plugins:
  - jekyll-remote-theme

remote_theme: "mmistakes/so-simple-theme@3.2.0"

title: "Tam's Crap"
description: "Freak of Nature"


# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/slowpowk
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/tamueljackson
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/letam
    icon: fab fa-github-square